### PR TITLE
Continue the process even if the build of a tool failed.

### LINKED ISSUE #132: Install tools that could be built or have been cached
See #130.

When building a tool failed, we should still install those whose build worked and those which were cached.

### PR DESCRIPTION
**Pull request by panglesd**
Fixes #132 

Currently, it still ends with an error, but the error message is a bit misleading without the context... Here is an output when the build of ocamlformat fails (the settings of the test):

```
opam@27c407da8c89:~/helloworld$ ocaml-platform
* Inferring tools version...                                                                                        
  -> dune is already installed
  -> dune-release.1.6.2 will be installed from cache
  -> merlin.4.6-413 will be installed from cache
  -> ocaml-lsp-server.1.10.5 will be installed from cache
  -> odoc.2.1.1 will be installed from cache
  -> ocamlformat.0.24.1 will be built from source
* Building the tools...
  -> Creating a sandbox...
  -> [1/1] Building ocamlformat...
ocaml-platform: [WARNING] There was an error during build of ocamlformat. Run with `-v` for more information.
* Installing tools...
  -> The following tools are now installed: odoc, ocaml-lsp-server, merlin, dune-release.
  -> The following tools haven't been installed: ocamlformat
* For more information on the platform tools, run `ocaml-platform --help`
ocaml-platform: [ERROR] Command 'opam install ocamlformat.0.24.1 --yes -q --color=never --switch
           /tmp/ocaml-platform-sandbox-9204f9 --root /home/opam/.opam' failed: exited with 40
opam@27c407da8c89:~/helloworld$
```

### CODE REVIEW

File: src/lib/tools.ml [hunk 1]
```diff
@@ -256,20 +271,31 @@ let install opam_opts tools =
...
+            (if tools_to_install = [] then "tool is" else "tools are")
+            Fmt.(list ~sep:(any ", ") string)
+            (List.map fst tools_to_install));
+      Ok tools_failed)
+  >>= fun tools_failed ->
+  if tools_not_installed <> [] || tools_failed <> [] then
+    Logs.app (fun m ->
+        let l = tools_not_installed @ List.map (fun x -> fst x) tools_failed in
+        m "  -> The following %s been installed: %a"
+          (if l = [] then "tool hasn't" else "tools haven't")
```
Comment (Julow) [inline src/lib/tools.ml:289]: Comparing with the empty list ? Do you mean `match l with [ _ ] -> ...` ?

File: src/lib/tools.ml [hunk 2]
```diff
@@ -224,27 +224,42 @@ let install opam_opts tools =
...
       Logs.app (fun m -> m "  -> All tools are already installed");
-      Ok ()
+      Ok []
   | _ ->
-      let+ () =
+      let tools_to_install =
+        let tools_failed_names = List.map (fun x -> fst x) tools_failed in
+        List.filter
+          (fun elem -> not (List.mem (fst elem) tools_failed_names))
+          tools_to_install
```
Comment (Julow) [inline src/lib/tools.ml:260]: Too smart for me. I would prefer if the list of `tools_built` was accumulated in the fold above.

File: test/tests/failing_ocamlformat.sh [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+opam update
+
+# We removed installed versions
+opam remove ocamlformat+bin+platform odoc+bin+platform
+
+# And force next installation to be 0.24.1
+sed -i 's/0.19.0/0.24.1/g' .ocamlformat
+
+# Run the installed
+ocaml-platform -vv || echo "Fails because ocamlformat builds failed"
```
Comment (Julow) [inline test/tests/failing_ocamlformat.sh:16]: To also assert that it exits with non-zero:

```suggestion
! ocaml-platform -vv
```

File: src/lib/tools.ml (hunk 2 above)
Comment (panglesd) [reply src/lib/tools.ml:260]: I made a version accumulating `tools_built` and modifying `to_install` into `in_cache`.

File: src/lib/tools.ml [hunk 4]
```diff
@@ -207,44 +207,61 @@ let install opam_opts tools =
...
+                    (i, ((tool_name, tool_version), build)) ->
+                 Logs.app (fun m ->
+                     m "  -> [%d/%d] Building %s..." (i + 1) n tool_name);
+                 match build sandbox with
+                 | Ok () ->
+                     ((tool_name, tool_version) :: tools_built, tools_failed)
+                 | Error e ->
+                     Logs.warn (fun m ->
+                         m
+                           "There was an error during build of %s. Run with \
```
Comment (Julow) [inline src/lib/tools.ml:251]: Nitpick: I think there's a better place for the "Run with -v ..." part in `if tools_failed <> []` below. Repeating the list of tools that failed there could be nice too.

File: src/lib/tools.ml [hunk 5]
```diff
@@ -207,44 +207,61 @@ let install opam_opts tools =
...
+                           tool_name);
+                     (tools_built, (tool_name, e) :: tools_failed))
+               ([], [])
+               (List.mapi (fun i s -> (i, s)) tools_to_build))))
+  >>= fun (tools_built, tools_failed) ->
+  (match (tools_in_cache, tools_to_build) with
+  | [], [] ->
       Logs.app (fun m -> m "  -> All tools are already installed");
-      Ok ()
+      Ok []
```
Comment (Julow) [inline src/lib/tools.ml:261]: I'm not sure about the meaning of this. Tools have already been built at this point and we already checked whether `tools_to_build` is empty above.
Also, it turns `tools_failed` into the empty list ?

Also, the list meaningful list for the code below is `tools_in_cache @ tools_built` and I don't even want to think about the relation with what's matched here.
The code in the wildcard case can already be run with an empty `tools_to_install` so it shouldn't be nested inside this match at least.

I suggest moving this message to the match on `tools_to_build`, possibly with a different message. Also, it would be closer to the code that make the plan on what to do.

File: src/lib/tools.ml [hunk 6]
```diff
@@ -256,20 +273,35 @@ let install opam_opts tools =
...
+            | _ -> "tools are")
+            Fmt.(list ~sep:(any ", ") string)
+            (List.map fst tools_to_install));
+      Ok tools_failed)
+  >>= fun tools_failed ->
+  if tools_non_installable <> [] || tools_failed <> [] then
+    Logs.app (fun m ->
+        let l =
+          tools_non_installable @ List.map (fun x -> fst x) tools_failed
+        in
```
Comment (Julow) [inline src/lib/tools.ml:293]:
```suggestion
        let l = tools_non_installable @ List.map fst tools_failed in
```
I generally don't do style suggestions but it could fit on one line :)

File: src/lib/tools.ml [hunk 7]
```diff
@@ -256,20 +273,35 @@ let install opam_opts tools =
...
-             platform tools, run `ocaml-platform --help`");
-      Logs.app (fun m -> m "* Success."))
-  >>= fun () ->
-  if tools_not_installed <> [] then
-    Logs.warn (fun m ->
-        m "The following tools haven't been installed: %a"
+          m "  -> The following %s now installed: %a."
+            (match tools_to_install with
+            | [ _ ] -> "tool is"
+            | _ -> "tools are")
```
Comment (Julow) [inline src/lib/tools.ml:284]: This seems like an improvement for now but I wouldn't be happy to see more of these. It's not very readable in the middle of the code. We should think of defining all the messages and their inputs in a separate module.

File: src/lib/tools.ml [hunk 8]
```diff
@@ -256,20 +273,35 @@ let install opam_opts tools =
...
+          (match l with [ _ ] -> "tool hasn't" | _ -> "tools haven't")
           Fmt.(list ~sep:(any ", ") string)
-          tools_not_installed);
-  Ok ()
+          l)
+  else Logs.app (fun m -> m "* Success.");
+  Logs.app (fun m ->
+      m
+        "* For more information on the platform tools, run `ocaml-platform \
+         --help`");
```
Comment (Julow) [inline src/lib/tools.ml:302]: This message doesn't make much sense if nothing was installed and doesn't add much if it's followed by errors. Perhaps it should be in the success case only ?

File: src/lib/tools.ml [hunk 9]
```diff
@@ -12,6 +12,75 @@ type tool = {
...
+  let conclusion tools_non_installable tools_failed =
+    let not_installed = tools_non_installable @ List.map fst tools_failed in
+    match not_installed with
+    | [] ->
+        Logs.app (fun m -> m "* Success.");
+        Logs.app (fun m ->
+            m
+              "* For more information on the platform tools, run \
+               `ocaml-platform --help`")
+    | [ tool ] ->
```
Comment (Julow) [inline src/lib/tools.ml:39]: This extra case was supposed to handle plural ? It's not. But now that we have a dedicated module, let's introduce a helper for plural: `"%a" ... (list_plural "tool" "tools") tools_not_installed`.

If you want to handle plural that is. I'd prefer not to.

**Review by Julow — APPROVED** [review]
As always I have something to say but after that, it's perfect.

File: src/lib/tools.ml (hunk 9 above)
Comment (panglesd) [reply src/lib/tools.ml:39]: Do you think it is better not to handle plural, that is to have:
```
The following tools haven't been installed: ocamlformat.
```
instead of
```
The following tool hasn't been installed: ocamlformat.
```

Comment (Julow) [reply src/lib/tools.ml]: I think it's unnecessary but nice to have. I would definitely prefer having a more maintainable code, so let's see if it can be implemented without bugs (perhaps using a `%a` helper) and without duplication (which is a source of bugs in the future).

File: src/lib/tools.ml [hunk 10]
```diff
@@ -12,6 +12,73 @@ type tool = {
   ocaml_version_dependent : bool;
 }
 
+module Communication = struct
+  let list_plural list singular plural ppf =
```
[the remark this answers is not in the document]
Comment (Julow) [reply src/lib/tools.ml:16]: In case of a `%t`, there's no question as I see that you changed it in your last commit.

[the remark this answers is not in the document]
Comment (panglesd) [reply src/lib/tools.ml]: Of course, it depends on what you think is "how to format" and what is "what to format".

For me, `(list_plural list)` is "how to format" (eg will we use the singular or the plural) and `("tool is", "tools are")` is what we want to format (a part of sentence that can be singular or plural).

However, this is just nitpicking, both views are valid and this discussion was already too long. I don't wan't to make it longer. I pushed your version, if you are happy with it, feel free to merge.

[the remark this answers is not in the document]
Comment (Julow) [reply src/lib/tools.ml]: Well, if the list is not a constant, it cannot be "how". Agree this is nitpick, let's merge when CI is green.
